{{- $logLevel := (coalesce .Values.logLevel .Values.log.level "INFO") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.annotations.config }}
  annotations:
    {{- toYaml .Values.annotations.config | nindent 4 }}
  {{- end }}
data:
  teleport.yaml: |
    teleport:
      auth_token: "/etc/teleport-secrets/auth-token"
      auth_servers: ["{{ required "proxyAddr is required in chart values" .Values.proxyAddr }}"]
      log:
        severity: {{ $logLevel }}
        output: {{ .Values.log.output }}
        format:
          output: {{ .Values.log.format }}
          extra_fields: {{ .Values.log.extraFields | toJson }}

    kubernetes_service:
      {{- if or (contains "kube" (.Values.roles | toString)) (empty .Values.roles) }}
      enabled: true
      kube_cluster_name: {{ required "kubeClusterName is required in chart values when kube role is enabled, see README" .Values.kubeClusterName }}
        {{- if .Values.labels }}
      labels: {{- toYaml .Values.labels | nindent 8 }}
        {{- end }}
      {{- else }}
      enabled: false
      {{- end }}

    app_service:
      {{- if contains "app" (.Values.roles | toString) }}
      enabled: true
      apps:
        {{- range $app := .Values.apps }}
          {{- if not (hasKey $app "name") }}
            {{- fail "'name' is required for all 'apps' in chart values when app role is enabled, see README" }}
          {{- end }}
          {{- if not (hasKey $app "uri") }}
            {{- fail "'uri' is required for all 'apps' in chart values when app role is enabled, see README" }}
          {{- end }}
        {{- end }}
      {{- required "'apps' map is required in chart values when app role is enabled, see README" .Values.apps | toYaml | nindent 8 }}
      {{- else }}
      enabled: false
      {{- end }}

    {{- /* specifying 'db_service' in a config file prior to Teleport 6 results in a parse error */ -}}
    {{- if semverCompare ">=6" (.teleportVersion | toString) }}

    db_service:
      {{- if contains "db" (.Values.roles | toString) }}
      enabled: true
      databases:
        {{- range $db := .Values.databases }}
          {{- if not (hasKey $db "name") }}
            {{- fail "'name' is required for all 'databases' in chart values when db role is enabled, see README" }}
          {{- end }}
          {{- if not (hasKey $db "uri") }}
            {{- fail "'uri' is required for all 'databases' is required in chart values when db role is enabled, see README" }}
          {{- end }}
          {{- if not (hasKey $db "protocol") }}
            {{- fail "'protocol' is required for all 'databases' in chart values when db role is enabled, see README" }}
          {{- end }}
        {{- end }}
        {{- required "'databases' map is required in chart values when db role is enabled, see README" .Values.databases | toYaml | nindent 8 }}
      {{- else }}
      enabled: false
      {{- end }}
    {{- end }}

    auth_service:
      enabled: false
    ssh_service:
      enabled: false
    proxy_service:
      enabled: false
